export type Customer = {
  code: string;
  name: string;
  nameGreek?: string;
  city: string;
  areaCode: string;
  area: string;
  type?: string;
  group?: string;
  lastVisitDate?: string;
  assignedRepId?: string;
  trdr_id?: number;
  salesmanCode?: string;
  afm?: string;
  address?: string;
  email?: string;
  fax?: string;
  zip?: string;
  shipmentName?: string;
  carrierName?: string;
  growth_pct?: number | null;
};